-- CREATE TABLE USER(
--     id int auto_increment primary key,
--     name varchar(255) not null,
--     email varchar(255) not null unique,
--     password varchar(255) not null,
--     created_at timestamp default current_timestamp,
--     updated_at timestamp default current_timestamp on update current_timestamp
-- )